name: Release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: build docker environment
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: instrew-env
      - name: build instrew
        run: docker run --rm -v "$PWD"/:/instrew/ instrew-env
      - name: bundle instrew
        run: mv install instrew && tar -czf instrew-x86_64.tar.gz instrew
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest_release
          release_name: latest
          draft: true
          prerelease: false
      - name: upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./instrew-x86_64.tar.gz
          asset_name: instrew-x86_64.tar.gz
          asset_content_type: application/gzip
      - name: publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
      - name: delete-previous-release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}